# Generated by Django 2.0.5 on 2018-05-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brotherhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('registered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('registered',),
            },
        ),
    ]
