# Generated by Django 2.0.5 on 2018-05-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brotherhoods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brotherhood',
            name='place',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
