# Generated by Django 2.0.5 on 2018-05-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brotherhoods', '0002_brotherhood_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brotherhood',
            name='place',
            field=models.IntegerField(editable=False),
        ),
    ]
