# Generated by Django 2.0.5 on 2018-05-29 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brotherhoods', '0003_auto_20180528_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brotherhood',
            options={'ordering': ('place',)},
        ),
    ]
