# Generated by Django 2.0.5 on 2018-05-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brotherhoods', '0004_auto_20180528_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brotherhood',
            name='place',
            field=models.IntegerField(),
        ),
    ]
