# Generated by Django 2.0.5 on 2018-05-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brotherhoods', '0005_auto_20180529_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brotherhood',
            name='place',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
